load("@rules_go//go:def.bzl", "go_library")
load("//tools/rules:com_tm_container.bzl", "com_tm_go_image")

go_library(
    name = "worker_lib",
    srcs = ["main.go"],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/services/core/cmd/worker",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/otelx",
        "//pkg/postgres",
        "//services/core/internal/config",
    ],
)

com_tm_go_image(
    name = "worker",
    embed = [":worker_lib"],
    image_name = "core-worker",
    visibility = ["//visibility:public"],
)
