load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "server_lib",
    srcs = [
        "config.go",
        "main.go",
    ],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/services/core/cmd/server",
    visibility = ["//visibility:private"],
    deps = [
        "//services/core/internal/httpx",
        "@com_github_jackc_pgx_v5//pgxpool",
    ],
)

go_binary(
    name = "server",
    embed = [":server_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "server_test",
    srcs = ["config_test.go"],
    embed = [":server_lib"],
)
