load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "otelx",
    srcs = ["log.go"],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/pkg/otelx",
    visibility = ["//visibility:public"],
)

go_test(
    name = "otelx_test",
    srcs = ["log_test.go"],
    embed = [":otelx"],
)
