load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "otelx",
    srcs = [
        "correlation.go",
        "log.go",
        "setup.go",
    ],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/pkg/otelx",
    visibility = ["//visibility:public"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel_exporters_otlp_otlpmetric_otlpmetrichttp//:otlpmetrichttp",
        "@io_opentelemetry_go_otel_exporters_otlp_otlptrace_otlptracehttp//:otlptracehttp",
        "@io_opentelemetry_go_otel_sdk//resource",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "otelx_test",
    srcs = [
        "log_test.go",
        "setup_test.go",
    ],
    embed = [":otelx"],
    deps = [
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//baggage",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)
