load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "httpx",
    srcs = [
        "middleware.go",
        "router.go",
        "serve.go",
    ],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/services/core/internal/httpx",
    visibility = ["//services/core:__subpackages__"],
    deps = [
        "//pkg/otelx",
        "@com_github_go_chi_chi_v5//:chi",
        "@com_github_go_chi_chi_v5//middleware",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "httpx_test",
    srcs = [
        "middleware_test.go",
        "router_test.go",
        "serve_test.go",
    ],
    embed = [":httpx"],
    deps = [
        "//pkg/otelx",
        "@com_github_go_chi_chi_v5//:chi",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk//trace/tracetest",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//metricdata",
    ],
)
