load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "postgres",
    srcs = [
        "pool.go",
        "tracer.go",
    ],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/pkg/postgres",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_exaring_otelpgx//:otelpgx",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "postgres_test",
    srcs = [
        "pool_test.go",
        "tracer_test.go",
    ],
    embed = [":postgres"],
    deps = [
        "@com_github_exaring_otelpgx//:otelpgx",
        "@com_github_jackc_pgx_v5//:pgx",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk//trace/tracetest",
    ],
)
