load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/toanmai8195/snaptix/com/tm/server/services/core/internal/config",
    visibility = ["//services/core:__subpackages__"],
    deps = ["//pkg/otelx"],
)

go_test(
    name = "config_test",
    srcs = ["config_test.go"],
    embed = [":config"],
)
